# Generated by Django 4.1.3 on 2023-01-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0003_cartoon_img_link'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartoon',
            table=None,
        ),
    ]
