# Generated by Django 4.1.3 on 2023-01-07 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0004_alter_cartoon_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartoon',
            table='cartoons',
        ),
    ]
