# Generated by Django 4.1.3 on 2023-01-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0005_alter_cartoon_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='popularity',
            field=models.CharField(max_length=100),
        ),
    ]
