# Generated by Django 4.1.3 on 2023-01-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0006_alter_cartoon_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='popularity',
            field=models.IntegerField(),
        ),
    ]
