# Generated by Django 4.1.3 on 2023-01-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table=None,
        ),
    ]
