# Generated by Django 4.1.3 on 2023-01-07 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table='movies',
        ),
    ]
