# Generated by Django 4.1.3 on 2023-01-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table=None,
        ),
    ]
